version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sopra-backend-prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: 80.74.149.100
      DATABASE_PORT: 3306
      DATABASE_USER: Klevis27
      DATABASE_PASSWORD: hh1#98Lv2
      DATABASE_NAME: sopra-fs25-group-42-db-production
    ports:
      - "8080:8080"
    networks:
      - sopra-network

networks:
  sopra-network:
    driver: bridge