version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sopra-backend-prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: 80.74.149.100
      DATABASE_PORT: 3306
      DATABASE_USER: your_db_user
      DATABASE_PASSWORD: your_db_password
      DATABASE_NAME: sopra-fs25-group-42-db-production
    ports:
      - "8080:8080"
    networks:
      - sopra-network
    command:
      - /wait-for-db.sh
      - 80.74.149.100:3306
      - --
      - java
      - -jar
      - /app/soprafs25.jar