version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sopra-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_HOST: mariadb-dev
      DATABASE_PORT: 3306
      DATABASE_USER: dev
      DATABASE_PASSWORD: dev
      DATABASE_NAME: sopra-mariadb-dev
      JWT_SECRET: QxkrD1mqZgFDM82gsV1rJ6cRfNdvMoH4
    ports:
      - "8080:8080"
    depends_on:
      - mariadb-dev
    networks:
      - sopra-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      - /wait-for-db.sh
      - mariadb-dev:3306
      - --
      - java
      - -jar
      - /app/soprafs25.jar

  mariadb-dev:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sopra-mariadb-dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sopra-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  websocket-server:
    build: yjs
    ports:
      - "1234:1234"
    networks:
      - sopra-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - sopra-network
    depends_on:
      - mariadb-dev

networks:
  sopra-network:
    driver: bridge

volumes:
  mariadb-data:
